In [1]:
2 + 7

9

In [2]:
x = 5

In [3]:
print(x)

5


In [4]:
# shift + enter

In [5]:
a =  [ [2,4] ,   [5,6]  ]

In [6]:
print(a)

[[2, 4], [5, 6]]


In [7]:
array( [ [2,4] ,   [5,6]  ] )

NameError: name 'array' is not defined

In [8]:
import numpy

In [10]:
b = numpy.array( [ [2,4] ,   [5,6]  ] )

In [11]:
print(b)

[[2 4]
 [5 6]]


In [14]:
b

array([[2, 4],
       [5, 6]])

In [18]:
b[: , 1]

array([4, 6])

In [16]:
print("hi")

hi


In [17]:
"hi"

'hi'

In [19]:
x = numpy.array( [[0,1], [1,0]] )

In [20]:
x

array([[0, 1],
       [1, 0]])

In [21]:
ket0 = numpy.array( [ [1], [0] ]) 

In [22]:
ket0

array([[1],
       [0]])

In [24]:
ket1 = numpy.dot( x, ket0 )

In [25]:
ket1

array([[0],
       [1]])